name: ${PROJECT}

networks:
  net:
    driver: bridge

services:
  traefik:
    image: "traefik:v2.10"
    env_file: .env
    command:
      - "--providers.docker.exposedbydefault=false"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: unless-stopped    
    container_name: "traefik"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`${HOST}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${AUTH}"
      - "traefik.http.middlewares.traefiksts.headers.stsincludesubdomains=false"
      - "traefik.http.middlewares.traefiksts.headers.stspreload=true"
      - "traefik.http.middlewares.traefiksts.headers.stsseconds=31536000"
      - "traefik.http.middlewares.traefiksts.headers.isdevelopment=false"
      - "traefik.http.middlewares.secured.chain.middlewares=traefiksts,auth"
      - "traefik.http.routers.traefik.middlewares=secured"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "1884:1884"
    networks:
      - net
    volumes:
      - "traefik_data:/letsencrypt"
      - "./:/etc/traefik"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  traefik_data:
