version: "3.9"

networks:
  net:
    driver: bridge

services:
  traefik:
    image: "traefik:v2.5"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: unless-stopped    
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=mh@qxf.de"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      #- "--providers.file.filename=/etc/traefik/cockpit.yaml"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.qxf.de`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=mh:$$apr1$$lhkpo2by$$HLxKuazUduO73EmHExZgs/"

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - net
    volumes:
      - "traefik_data:/letsencrypt"
      - "~/Traefik:/etc/traefik"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  traefik_data:
