entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: :443

api:
  dashboard: true
  insecure: true

providers:
  docker: {}
  file:
    directory: /etc/traefik
    watch: true

certificatesResolvers:
  myresolver:
    acme:
      email: "mh@qxf.de"
      storage: "/letsencrypt/acme.json"
      httpChallenge:
        entryPoint: web
tls:
  options:
    default:
      minVersion: VersionTLS13
